#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("KBC.Resource", IsApplication=true)]

namespace KBC
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int theme_devicedefault_background = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int audience = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int change = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int doubleDip = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int fifty50 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Splash = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080008
			public const int audiencePollButton = 2131230728;
			
			// aapt resource value: 0x7f08000c
			public const int cashView = 2131230732;
			
			// aapt resource value: 0x7f08000b
			public const int changeQuestionButton = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int doubleDipButton = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int fifty50Button = 2131230729;
			
			// aapt resource value: 0x7f080017
			public const int helpButton = 2131230743;
			
			// aapt resource value: 0x7f08001b
			public const int lifelinesUsedView = 2131230747;
			
			// aapt resource value: 0x7f080015
			public const int moneyTeeContainer = 2131230741;
			
			// aapt resource value: 0x7f080018
			public const int moneyTree = 2131230744;
			
			// aapt resource value: 0x7f080016
			public const int newGameButton = 2131230742;
			
			// aapt resource value: 0x7f080011
			public const int optionA = 2131230737;
			
			// aapt resource value: 0x7f080001
			public const int optionABar = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int optionACent = 2131230720;
			
			// aapt resource value: 0x7f080012
			public const int optionB = 2131230738;
			
			// aapt resource value: 0x7f080003
			public const int optionBBar = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int optionBCent = 2131230722;
			
			// aapt resource value: 0x7f080013
			public const int optionC = 2131230739;
			
			// aapt resource value: 0x7f080005
			public const int optionCBar = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int optionCCent = 2131230724;
			
			// aapt resource value: 0x7f080014
			public const int optionD = 2131230740;
			
			// aapt resource value: 0x7f080007
			public const int optionDBar = 2131230727;
			
			// aapt resource value: 0x7f080006
			public const int optionDCent = 2131230726;
			
			// aapt resource value: 0x7f08001c
			public const int playAgainButton = 2131230748;
			
			// aapt resource value: 0x7f080010
			public const int questionView = 2131230736;
			
			// aapt resource value: 0x7f08001a
			public const int resultCashView = 2131230746;
			
			// aapt resource value: 0x7f080019
			public const int resultMessageView = 2131230745;
			
			// aapt resource value: 0x7f08000d
			public const int timerLayout = 2131230733;
			
			// aapt resource value: 0x7f08000f
			public const int timerProgress = 2131230735;
			
			// aapt resource value: 0x7f08000e
			public const int timerView = 2131230734;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int AudiencePoll = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Game = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Help = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Main = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int MoneyTree = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Result = 2130968581;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Custom = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
