#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("KBC.Resource", IsApplication=true)]

namespace KBC
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070000
			public const int theme_devicedefault_background = 2131165184;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int audience = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int change = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int doubleDip = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int fifty50 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Splash = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090008
			public const int audiencePollButton = 2131296264;
			
			// aapt resource value: 0x7f09000c
			public const int cashView = 2131296268;
			
			// aapt resource value: 0x7f09000b
			public const int changeQuestionButton = 2131296267;
			
			// aapt resource value: 0x7f09000a
			public const int doubleDipButton = 2131296266;
			
			// aapt resource value: 0x7f090009
			public const int fifty50Button = 2131296265;
			
			// aapt resource value: 0x7f090017
			public const int helpButton = 2131296279;
			
			// aapt resource value: 0x7f09001c
			public const int lifelinesUsedView = 2131296284;
			
			// aapt resource value: 0x7f090015
			public const int moneyTeeContainer = 2131296277;
			
			// aapt resource value: 0x7f090019
			public const int moneyTree = 2131296281;
			
			// aapt resource value: 0x7f090016
			public const int newGameButton = 2131296278;
			
			// aapt resource value: 0x7f090011
			public const int optionA = 2131296273;
			
			// aapt resource value: 0x7f090001
			public const int optionABar = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int optionACent = 2131296256;
			
			// aapt resource value: 0x7f090012
			public const int optionB = 2131296274;
			
			// aapt resource value: 0x7f090003
			public const int optionBBar = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int optionBCent = 2131296258;
			
			// aapt resource value: 0x7f090013
			public const int optionC = 2131296275;
			
			// aapt resource value: 0x7f090005
			public const int optionCBar = 2131296261;
			
			// aapt resource value: 0x7f090004
			public const int optionCCent = 2131296260;
			
			// aapt resource value: 0x7f090014
			public const int optionD = 2131296276;
			
			// aapt resource value: 0x7f090007
			public const int optionDBar = 2131296263;
			
			// aapt resource value: 0x7f090006
			public const int optionDCent = 2131296262;
			
			// aapt resource value: 0x7f09001d
			public const int playAgainButton = 2131296285;
			
			// aapt resource value: 0x7f090018
			public const int playSoundsCheck = 2131296280;
			
			// aapt resource value: 0x7f090010
			public const int questionView = 2131296272;
			
			// aapt resource value: 0x7f09001b
			public const int resultCashView = 2131296283;
			
			// aapt resource value: 0x7f09001a
			public const int resultMessageView = 2131296282;
			
			// aapt resource value: 0x7f09000d
			public const int timerLayout = 2131296269;
			
			// aapt resource value: 0x7f09000f
			public const int timerProgress = 2131296271;
			
			// aapt resource value: 0x7f09000e
			public const int timerView = 2131296270;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int AudiencePoll = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Game = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Help = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Main = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int MoneyTree = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Result = 2130968581;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int Correct = 2131034112;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int Theme_Custom = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
