namespace KBC
{
    static class Questions
    {
        public static Question[] Easy { get; } =
        {
            new Question("Which of these sounds would you associate with the heart?", "Tring Tring", "Tap Tap", "Click Click", "Dhak Dhak", 4),
            new Question("With which of these cards would you associate the phrase 'Aam Aadmi ka Adhikaar'?", "PAN Card", "Voter ID Card", "AADHAR Card", "Ration Card", 3),
            new Question("Which of these is not a recommended mineral in human diet?", "Strontium", "Potassium", "Iron", "Calcium", 1),            
            new Question("Penguin, Ostrich, Emu and Kiwi have what in common", "Similar shapes", "Can not fly", "Can not walk", "Can not see", 2),
            new Question("The black widow, which eats the male counterpart after mating, is a female species of which animal?", "Sloth", "Ant", "Spider", "Termite", 3),
            new Question("Gandhiji's thought of 'See no evil, hear no evil, speak no evil' is usually depicted by which animal?", "Lion", "Elephant", "Bear", "Monkey", 4),
            new Question("Which of these spices that are given here cost most among them?", "Vanilla", "Cardamom", "Black Pepper", "Saffron", 4),
            new Question("In 2013, where did the natural calamity known as Himalayan tsunami occur?", "Uttrakhand", "Arunachal Pradesh", "Jammu and Kashmir", "Sikkim", 1),
            new Question("With which of these states do Chhattisgarh, Jharkhand and Andhra Pradesh all share their borders?", "Madhya Pradesh", "Odisha", "Bihar", "Uttar Pradesh", 2),
            new Question("Which of these is a piece of the game called as chess?", "Wazir", "Nawab", "Sarpanch", "Patbari", 1),
            new Question("Which is the largest banana producing country in the world?", "Brazil", "India", "Mexico", "China", 2),
            new Question("In Ramayana, who reminded kaikeyi about the two boons given to her by Dasharatha?", "Sumitra", "Bharata", "Dasharatha", "Manthara", 4),
            new Question("Which of these words means 'water'?", "Rahul", "Sanjay", "Varun", "Rajiv", 3),
            new Question("After whom is the Centigrade system of temperature measurement named?", "Anders Celcius", "Daniel Fahrenheit", "Lord Kelvin", "Gabriele Centi", 1),
            new Question("Which of these festivals is celebrated in honour of an avatar of Lord Vishnu?", "Janmashtami", "Ganesha Chaturthi", "Vishwakarma", "Maha Shivaratri", 1),
            new Question("In the human body, what makes the pupil of an eye contract or dilate?", "Hunger", "Thirst", "Light", "Sound", 3),
            new Question("Which of these sportsmen started his career as a travelling ticket examiner with Indian Railways?", "Bhuvneshwar Kumar", "Shikhar Dhawan", "Ravinder Jadeja", "Mahendra Singh Dhoni", 4),
            new Question("The increased level of which of these causes more humidity in the air?", "Dust", "Water vapour", "Smoke", "Sunlight", 2),
            new Question("Which of these is not a type of vitamin", "Vitmain A", "Vitamin X", "Vitamin E", "Vitamin K", 2),
            new Question("The newborn of which of these mammals weighs the heaviest?", "Blue Whale", "African Elephant", "Hippopotamus", "Giant Panda", 1),
            new Question("Which one of these states is the largest in area?", "Assam", "Arunachal Pradesh", "Punjab", "Haryana", 2),
            new Question("In geometry, if a shape has only three sides namely A, B and C, then what shape would that be?", "Rectangle", "Square", "Triangle", "Pentagon", 3),
            new Question("Which of these is not a computer operating system?", "Apple OS X", "Linux", "Windows 8", "Adobe Photoshop", 4),
            new Question("Which of these is not among the four Vedas?", "Yajur", "Ayurved", "Rig", "Sama", 2),
            new Question("Which vitamin helps with blood clothing", "A", "B", "C", "K", 4),
            new Question("In a circle, which of these is half of the diameter?", "Area", "Centre", "Circumference", "Radius", 4),
            new Question("About whom did the poet write, 'Lakshmi thi yaa Durga thi woh swayam veerta ki avatar, dekh marathe pulkit hote uski talwaaroke ke waar?'", "Rani Durgavati", "Jhansi ki rani", "Rani Ahilyabai Holkar", "Rani Padmavati", 2),
            new Question("Which of these gases is named for it’s color?", "Helium", "Methane", "Oxygen", "Chlorine", 4),
            new Question("Which aspect about a person is known by the words 'natkhat' and 'manmauji'?", "Height", "Skin Colour", "Nature", "Marital Status", 3),
            new Question("Which demon is shown alongside goddess Durga in puja pandals during the traditional Durga Puja celebrations?", "Bakasura", "Vanasura", "Bhasmasura", "Mahisashura", 4),
            new Question("In which of these sports are the terms reverse swing and reverse sweep used?", "Football", "Cricket", "Badminton", "Tennis", 2),
            new Question("Damascus is the capital of which country?", "Tunisia", "Jordan", "Syria", "Lebanon", 3),
            new Question("Which of the following gods is also known as 'Gauri Nandan'?", "Agni", "Ganesha", "Indra", "Hanuman", 2),
            new Question("In the game of ludo the discs or tokens are of how many colours?", "Three", "Two", "One", "Four", 4),
            new Question("Which of these sports requires you to shout out a word loudly during play?", "Chess", "Ludo", "Playing cards", "Kho-kho", 4),
            new Question("Which of these spices is the smallest in size?", "Jeera", "Saunf", "Ajwain", "Methi Seeds", 3),
            new Question("Which of these stages is one of the four stages of human life in ancient Indian tradition?", "Dronacharya", "Vasudevacharya", "Kripacharya", "Bramhacharya", 4),
            new Question("In which of these two sports is the term 'free hit' used?", "Football, Squash", "Badminton, Tennis", "Hockey, Cricket", "Boxing, Wrestling", 3),
            new Question("Which of these medical conditions is most likely to cause dehydration?", "Malaria", "Tetanus", "Beriberi", "Diarrhoea", 4),
            new Question("Which of these sports has 22 players playing on the field at the same time?", "Cricket", "Hockey", "Rugby", "Badminton", 2),
            new Question("Which of these is measured with the help of a glucometer?", "Heartbeat", "Blood pressure", "Blood Sugar", "Vision", 3),
            new Question("With which of these states does Telengana not share its border?", "Tamil Nadu", "Karnataka", "Chattisgarh", "Maharashtra", 1),
            new Question("How many watts equal a megawatt?", "One Hundred", "One Thousand", "Ten Thousand", "One Lakh", 4),
            new Question("Which of these numbers is only divisible by 1 and itself?", "12", "13", "14", "15", 2),            
        };

        public static Question[] Medium { get; } =
        {            
            new Question("In the Ramayana, Which demon impersonated Rama's voice, screaming, 'Lakshman! Help Me!'?", "Surpanakha", "Khara", "Maricha", "Dushana", 3),
            new Question("Who is the only leader to be elected Prime Minister of Pakistan three times", "Syed Yousaf Raza Gillani", "Benazir Bhutto", "Liaqat Ali Khan", "Nawaz Sharif", 4),
            new Question("Douglas Engelbert, who passed away in 2013, is credited as the inventor of which of these products?", "Mobile Phone", "Computer Mouse", "Bluetooth Mouse", "Digital Camera", 2),
            new Question("Which of the following person has not walked on the moon?", "Charles Duke", "James A Lovell", "Alan Bean", "Pete Conrad", 2),
            new Question("Which team retained the ashes Trophy in 2013?", "Australia", "South Africa", "West Indies", "England", 4),
            new Question("The first world championship of what sport is planned to be held in 2017, though the game has been played since 1877?", "Test Cricket", "Rugby Union", "Kabaddi", "Carrom", 1),
            new Question("Which is the largest living species of tortoise in the world, which may weigh about 400 kg?", "Sulcata Tortoise", "Grenada Tortoise", "Golden Greek Tortoise", "Galapagos Tortoise", 4),
            new Question("According to legend, which of these Rishis regained his youth by a celestial favour?", "Agastya", "Durvasa", "Chyavana", "Charaka", 3),
            new Question("Which of these is a term for a place where people gather for shayari and ghazals?", "Rukhsar", "Mushaira", "Shikara", "Mahabara", 2),
            new Question("Who was the president of India at the turn of the century, as the 20th century became the 21st century?", "K R Narayan", "A P J Abdul Kalam", "R Venkataraman", "Shankar Dayal Sharma", 1),
            new Question("In the Mughal era, which of these harbours was also known as 'Babul Mecca' and 'Meccaidwar'?", "Bharuch", "Surat", "Porbandar", "Khambat", 2),
            new Question("To respect whose word did the five Pandavas marry Draupadi?", "Krishna", "Indra", "Kunti", "Madri", 3),
            new Question("Who is the only Indian to have won a medal in Women's Singles at the World Badminton Championships?", "Jwala Gupta", "P V Sindhu", "Saina Nehwal", "Ashwini Ponnappa", 2),
            new Question("From which country did India buy an aircraft carrier which was renamed as INS Vikramaditya?", "France", "Russia", "England", "Germany", 2),
            new Question("Which of these cricket tournaments is referred to as the 'Mini World Cup'?", "Natwest Series", "Asia Cup", "ICC Championship Trophy", "Twenty20 World Cup", 3),
            new Question("Lord Krishna earned which of the following names because he killed a particular demon?", "Kanhya", "Murari", "Jagannath", "Govind", 2),
            new Question("In July 2013, Indian highest judicial court issued a rule that anybody who wants to buy which of these has to show his identity card?", "Alcohol", "Sandalwood", "Gold", "Acid", 4),
            new Question("Which gas is the most reactive of all chemical elements?", "Oxygen", "Chlorine", "Flourine", "Hydrogen", 3),
            new Question("NR Narayana Murthy was appointed Executive Chairman of which IT Giant in 2013?", "Infosys", "TCS", "WIPRO", "HCL", 1),
            new Question("BP Mandal, who chaired the second backward classes commission, also known as Mandal commission, served as chief minister of which state?", "Uttar Pradesh", "Bihar", "West Bengal", "Odisha", 2),
            new Question("Who is the author of the poem 'Where the mind is without fear'?", "Muhammad Iqbal", "Bankim Chandra Chatterjee", "RabindraNath Tagore", "Sri Aurobindo", 3),
            new Question("To reach which of these places do pilgrims start their journey on foot from Gauri Kund?", "Badrinath", "Kedarnath", "Vaishano Devi", "Amarnath", 2),
            new Question("Which of these terms is used to denote food that is permissible for consumption according to Islamic law?", "Jhatka", "Haram", "Halal", "Kosher", 3),
            new Question("In 1850, the first experimental electric telegraph line in India was set up between Calcutta and which place?", "Diamond Harbour", "Darjeeling", "Murshidabad", "Dhaka", 1),
            new Question("After whom is the annual award, given by the Govt of India to an outstanding handloom weaver, named?", "Acharya Vinoba Bhave", "Sant Kabir", "Mahatma Gandhi", "Gul Ahmed", 2),
            new Question("Which of these freedom fighters was the English language secretary to Mahatma Gandhi for 16 years?", "Hansa Mehta", "Rajkumari Amrit Kaur", "Sarojini Naidu", "Sushila Nayyar", 2),
            new Question("Where was Durga Shakti Nagpal, IAS, serving when she was suspended by the UP Govt?", "Sant Ravidas Nagar", "Sant Kabir Nagar", "Ambedhkar Nagar", "Gautam Buddh Nagar", 4),
            new Question("Who is the first women amputee in the world to summit Mount Everest?", "Tashi Malik", "Raha Moharrak", "Samina Baig", "Arunima Sinha", 4),
            new Question("The tomb of which Governer-General of India is located in Ghazipur in Uttar Pradesh?", "Sir John Shore", "Lord Curzon", "Lord Cornwallis", "Lord Chelmsford", 3),
            new Question("In Which of these regions would you find the town of Kishtwar?", "Jammu", "Vidarbha", "Saurashtra", "Bundelkhand", 1),
            new Question("What disease, ascribed to a deficiency of vitamin B1, gets its name from a Sinhalese word for 'weakness'?", "Anaemia", "Riboflavin", "Beriberi", "Kala-azar", 3),
            new Question("In the year 2013, Which of these players was given the Rajiv Gandhi Khel Ratna award?", "Virat Kohli", "Ronjon Sodhi", "M. S. Dhoni", "Sachin Tendulkar", 2),
            new Question("To what post was P Sathasivam appointed in July 2013?", "CBI Director", "Chief Justice of India", "Chief Election Commissioner", "National Security Advisor", 2),
            new Question("Which sportsman's 108th birth anniversary was celebrated on 29 Aug 2013?", "Dhyan Chand", "Ranjitsinhji", "C K Nayudu", "I A K Pataudi", 1),
            new Question("What was the code name of the operation by IPKF to take control of Jaffna from the LTTE in 1987?", "Operation Cyclone", "Operation Meghdoot", "Operation Cactus", "Operator Pawan", 4),
            new Question("Which of these cities is not named after its founder or a dynasty?", "Bikaner", "Ludhiana", "Khajuraho", "Jodhpur", 3),
            new Question("Who is the youngest person ever to win a Nobel Prize?", "Lawrence Bragg", "Tsung-Dao Lee", "Werner Heisenberg", "Cal Anderson", 1),
            new Question("Which of these creatures does not have both the male and female reproductive organs in the same body (Hermaphrodites)?", "Earthworm", "Snail", "Black Sea Bass", "Termite", 4),
            new Question("Which of these parties broke away from the NDA in June 2013, after a 17-year long alliance?", "Janata Dal (S)", "Telugu Desam Party", "Janata Dal (United)", "Biju Janata Dal", 3),
            new Question("Which poem are these lines from: 'Nari tum keval Shraddha ho, Vishwas-rajat-nag- pagtal mein, Piyush-srot-si baha karo, Jivan ke sunder samtal hein'?", "Aansu", "Prem Pathik", "Kaanan Kusum", "Kamayani", 4),
            new Question("Which is the only country, apart from India, where one can find the Indian rhinoceros in its natural Habitat?", "Bangaldesh", "Nepal", "China", "Sri Lanka", 2),
            new Question("What type of naval vehicle is the INS Sindhurakshak?", "Destroyer", "Submarine", "Aircraft Carrier", "Patrol Vehicle", 2),
            new Question("Which place of worship is located between the Nar and Narayan mountains?", "Kedarnath", "Badrinath", "Amarnath Cave", "Vaishno Devi", 2),
            new Question("In which city was Vasco Da Gama first buried?", "Calicut", "Diu", "Vasco Da Gama", "Cochin", 4),
            new Question("Which of these Indian cricketers are brothers?", "Irfan and Yusuf Pathan", "Ravindra and Ajay Jadeja", "Bhuvneshwar and Vinay Kumar", "Ishant and Rohit Sharma", 1),
            new Question("What is the name of the dancing form of Lord Shiva that gained prominence in India during the Chola period?", "Rudra", "Nataraja", "Ardhanarishwara", "Bhairava", 2),
            new Question("In which district of Chhattisgarh did Maoists attack a convoy of Congress leaders on 25 May 2013?", "Sukma", "Bastar", "Dantewada", "Mahasamund", 2),
            new Question("Which of these personalities has also served as Deputy prime Minister of India?", "Lal Bahadur Shastri", "L K Advani", "Gulzarilal nanda", "Arjun Singh", 2),
            new Question("What name was given to the operation by the Indian Army to rescue stranded travellers from Uttarakhand during the 2013 floods?", "Operation Sukun", "Operation Asha", "Operation Flood", "Operation Surya Hope", 4),
            new Question("What is India's first ingeniously developed passenger car?", "Maruti 800", "Tata Indica", "Premier Padmini", "Ambassador", 2),
            new Question("Where was Indian diplomat Devyani Khobragade posted when she was arrested in a visa case in 2013?", "England", "Switzerland", "USA", "Russia", 3),
            new Question("Which queen did Draupadi,the wife of five pandavas, serve in the guise of Sairandhri for one year?", "Sanjana", "Satyavati", "Satyabhama", "Sudeshna", 4),
            new Question("Which newspaper once kept its editorial cloumn blank as a mark of protest against the emergency of 1975?", "Hindustan Times", "The Indian Express", "The Hindu", "The Times of India", 2),
            new Question("Which dance form is believed to have been inspired from Gotipua Nritya?", "Manipuri", "Kuchipudi", "Odissi", "Kathakali", 3),
            new Question("Who became the chief minister of Bihar in 2014?", "Nitish Kumar", "Vijay Kumar Chaudhary", "Narendra Narayan Yadav", "Jeetan Ram Majhi", 4),
            new Question("Which of these temples is located in Kathmandu,the capital of Nepal?", "Kamakhya Temple", "Pashupatinath Temple", "Viswanath Temple", "Baba Baidyanath Temple", 2),
            new Question("Who was the first deaf-blind person to receive a bachelor of arts degree?", "Alice Betteridge", "Helen Keller", "Laura Bridgman", "Sanzan Tani", 2),
            new Question("Which of these tiger reserves in India is adjacent to Chitwan National park in Nepal?", "Dudhwa", "Corbett", "Valmiki", "Buxa", 3),
            new Question("17. Which celebrated Italian film maker on a visit to India fell in love with a Bengali lady, Sonali Dasgupta?", "Sergio Leone", "Federico Fellini", "Roberto Rossellini", "Luchino Visconti", 3),
            new Question("Which of these are names of national parks located in Madhya Pradesh?", "Krishna and Kanhaiya", "Ghanshyam and Murari", "Kanha and Madhav", "Girdhar and Gopal", 3),
            new Question("Where was the BRICS summit held in 2014?", "Brazil", "India", "Russia", "China", 1),
            new Question("Who wrote the introduction to the English translation of Rabindranath Tagore’s Gitanjali?", "P. B. Shelley", "T.S. Elliot", "W. B. Yeats", "Alfred Tennyson", 3),
            new Question("Which of these leaders was a recipient of a gallantry award in 1987 by a state government for saving two girls from drowning?", "Mamata Banerjee", "Anandiben Patel", "Vasundhara Raje Scindia", "Uma Bharti", 2),
            new Question("The wife of which of these famous sportspersons was once captain of Indian volleyball team?", "K.D. Jadav", "Milkha Singh", "Dhyan Chand", "Prakash Padukone", 2),
            new Question("If Jwala Gutta and Ashwini compete as partners, in which sport are they participating?", "Tennis", "Badminton", "Squash", "Table Tennis", 2),
            new Question("Which battle in 1757 marked the beginning of British occupation in India?", "Buxar", "Cuddalore", "Plassey", "Assaye", 3),
            new Question("What kind of creature was Bakasur, whom Kansa sent to kill Sri Krishna in his childhood?", "Bird", "Snake", "Lizard", "Deer", 1),
            new Question("Which is the second most spoken language of Nepal?", "Bajjika", "Magahi", "Bhojpuri", "Maithili", 4),
            new Question("Who are the only married couple elected to the 16th Lok Sabha?", "Sukhbir Singh-Harshimrat Kaur Badal", "Pappu Yadav-Ranjeet Ranjan", "Prakash-Brinda Karat", "Priya Ranjan-Deepa Dasmunshi", 2),
            new Question("In which state is the Larji Hydroelectric Power Project located?", "Uttarakhand", "Himachal Pradesh", "Sikkim", "Jammu and Kashmir", 2),
            new Question("During which of these legendary events did Lord Vishnu take the form of Kurma?", "Hiranyakashipu Sanhar", "Kaliya Naag Mardan", "Samudra Manthan", "Kurukshetra Yudh", 3),
            new Question("Effective on may 2014,the European union imposed a temporary ban on the import of which of these fruits from India?", "Banana", "Litchi", "Mango", "Pineapple", 3),
            new Question("Where did Homi Jehangir Bhaba,the principal architect of India’s nuclear program, die in a plane crash?", "Mont Blanc", "Monte Rosa", "Mount Ararat", "Mount Elbrus", 1),
            new Question("Whose autobiography is titled 'Man of Everest' also published as 'Tiger of the snows'?", "Sir Edmund Hillary", "George Mallory", "Major H P S Aluhwalia", "Tenzing Norgay", 4),
            new Question("Which of these countries is larger than India in territorial space?", "Australia", "Argentina", "Kazakhstan", "Iran", 1),
            new Question("Who became the first woman director in the board of Reliance Industries?", "Kokilaben Ambani", "Deepti Salgaonkar", "Nitu Ambani", "Nina Kothari", 3),
            new Question("Which of these battles didn’t involve the Mughal army?", "Battle of Buxar", "Battle of Haldighati", "Second Battle of Panipath", "Third Battle of Panipath", 4),
            new Question("Before 2014,when was the last time in India that a single party majority was formed at the centre?", "1991", "1990", "1984", "1999", 3),
            new Question("What discovery in 1823 is credited to the British official Robert Bruce?", "Oil", "Tea", "Murga Silk", "Jute", 2),
            new Question("Which of these is not a Dravidian language?", "Tamil", "Karnataka", "Malyalam", "Assamese", 4),
            new Question("In 2014,on which ground did India win a test match after 28 years?", "The Oval", "MCG", "Lord’s", "Bristol", 3),
            new Question("Which of these animals is the largest member of the dog family?", "Jackal", "Hyena", "Wolf", "Fox", 3),
        };
    }
}