#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("KBC.Resource", IsApplication=true)]

namespace KBC
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int theme_devicedefault_background = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Splash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000f
			public const int audiencePollButton = 2131230735;
			
			// aapt resource value: 0x7f080008
			public const int cashView = 2131230728;
			
			// aapt resource value: 0x7f080012
			public const int changeQuestionButton = 2131230738;
			
			// aapt resource value: 0x7f080011
			public const int doubleTipButton = 2131230737;
			
			// aapt resource value: 0x7f080010
			public const int fifty50Button = 2131230736;
			
			// aapt resource value: 0x7f080014
			public const int moneyTree = 2131230740;
			
			// aapt resource value: 0x7f08000e
			public const int moneyTreeButton = 2131230734;
			
			// aapt resource value: 0x7f080013
			public const int newGameButton = 2131230739;
			
			// aapt resource value: 0x7f08000a
			public const int optionA = 2131230730;
			
			// aapt resource value: 0x7f080001
			public const int optionABar = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int optionACent = 2131230720;
			
			// aapt resource value: 0x7f08000b
			public const int optionB = 2131230731;
			
			// aapt resource value: 0x7f080003
			public const int optionBBar = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int optionBCent = 2131230722;
			
			// aapt resource value: 0x7f08000c
			public const int optionC = 2131230732;
			
			// aapt resource value: 0x7f080005
			public const int optionCBar = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int optionCCent = 2131230724;
			
			// aapt resource value: 0x7f08000d
			public const int optionD = 2131230733;
			
			// aapt resource value: 0x7f080007
			public const int optionDBar = 2131230727;
			
			// aapt resource value: 0x7f080006
			public const int optionDCent = 2131230726;
			
			// aapt resource value: 0x7f080017
			public const int playAgainButton = 2131230743;
			
			// aapt resource value: 0x7f080009
			public const int questionView = 2131230729;
			
			// aapt resource value: 0x7f080016
			public const int resultCashView = 2131230742;
			
			// aapt resource value: 0x7f080015
			public const int resultMessageView = 2131230741;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AudiencePoll = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Game = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MoneyTree = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Result = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int Correct = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Intro = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Question = 2130968578;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Custom = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
